//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Carts = new HashSet<Cart>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int Oid { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
        public Nullable<double> Payment { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
